services:
  - type: web
    name: melcho-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
